feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 78 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 500 # 1000
laser_point_cov : 0.001 # 0.001

cam_fx: 1166.05796578
cam_fy: 1167.12035962
cam_cx: 790.77882567
cam_cy: 573.01344767

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    90
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:

    img_topic:  /webcam/image_raw
    # Rcl: [0.00864993, -0.999865, -0.0139749, 
    #     -0.0117493, 0.0138728, -0.999835, 
    #     0.999894, 0.00881269, -0.0116277]


    # Pcl: [-0.0680744,0.00872503,-0.0423214]

    Rcl: [0.0177035,-0.999683,-0.0179272,
        0.0113121,0.0181291,-0.999772,
        0.999779,0.0174967,0.0116294]
    Pcl: [-0.0798385,0.017032,-0.0497419]

# feature_extract_enable : 0
# point_filter_num : 2
# max_iteration : 10
# dense_map_enable : 1
# filter_size_surf : 0.15
# filter_size_map : 0.3
# cube_side_length : 20
# grid_size : 40
# patch_size : 8
# img_enable : 1
# lidar_enable : 1
# outlier_threshold : 300 # 78 100 156
# ncc_en: false
# ncc_thre: 0
# img_point_cov : 100 # 1000
# laser_point_cov : 0.001 # 0.001
# delta_time: 0.0

# common:
#     lid_topic:  "/livox/lidar"
#     imu_topic:  "/livox/imu"

# preprocess:
#     lidar_type: 1 # 1:Livox Avia LiDAR  2:VELO16  3:OUST64  4:XT32 
#     scan_line: 6 # 16  64  32
#     blind: 5 # blind x m disable

# mapping:
#     acc_cov_scale: 100
#     gyr_cov_scale: 10000
#     extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
#     extrinsic_R: [ 1, 0, 0,
#                    0, 1, 0,
#                    0, 0, 1]

# pcd_save:
#     pcd_save_en: false

# camera:
#     img_topic: /left_camera/image
#     Rcl: [0.00162756,-0.999991,0.00390957,
#          -0.0126748,-0.00392989,-0.999912,
#           0.999918,0.00157786,-0.012681]
#     Pcl: [0.0409257, 0.0318424, -0.0927219]
    